### ISSUE TITLE
All the dcm files are converting instead of single file

### ISSUE THREAD

**Issue by ninjakx** [FNNDSC/med2image#23]
The code is converting all the dcm files.
`med2image -i 000002.dcm -o 000002.png`

**Comment by arushivyas** [comment]
The code is designed such that even though any one .dcm from the directory is passed to the `--inputFile` argument, all the `.dcm` files/slices in the directory that you provided will be converted.

In order to convert a particular slice from the directory, you will have to pass the slice number that you want to convert to the `--sliceToConvert` argument.
